# This is a basic workflow to help you get started with Actions

name: my-awesome-stars

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
  schedule:
  - cron: 30 0 * * *

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  my-awesome-stars:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # setup python
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      
      # Install dependencies using the runners shell
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install starred
          
      # Update repo
      - name: update repo
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          starred --username Nabeelhassan --repository my-awesome-stars --sort --token ${GITHUB_TOKEN} --message 'stars update by github actions cron'
        
      - name: Markdown to HTML
        uses: ZacJW/markdown-html-action@1.1.1
        with:
          input_files: '["README.md"]'
          output_files: '["index.html"]'

