name: update my-awesome-stars
on:
  workflow_dispatch:
  schedule:
  - cron: 30 0 * * *
jobs:
  my-awesome-stars:
    name: update my-awesome-stars
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install starred
    - name: update repo
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN_MY_AWESOME_STARS }}
      run: starred --username Nabeelhassan --repository my-awesome-stars --sort --token ${GITHUB_TOKEN} --message 'docs: stars updated by github actions cron'
